### PR TITLE
Initial Synology install instruction commit

### PR DESCRIPTION
**Pull request by shall0pass**
Draft instructions to install Actual on a Synology device.

### CODE REVIEW

**Comment by shall0pass** [comment]
Don't merge this yet.  I'm still working on it.

**Comment by rich-howell** [comment]
> Don't merge this yet. I'm still working on it.

Awesome @shall0pass, thanks for this, in `sidebar.js` if you have files with no content or will be populated later can they be listed like this

```js
items: [
            unavailable('Synology Reverse Proxy'),
            'Installing/synology-watchtower',
          ]
```

That will allow them to show as non-clickable in the tree.

**Comment by shall0pass** [comment]
Thanks Rich.  I saw that syntax in another page, but I felt I would get to it quickly enough that it wouldn't be much of an issue.  I think I'm through the 3 pages I wanted to add now as far as content goes.  It's ready to be further refined/proofread now and fix any formatting to make it match the rest of the docs.

**Comment by rich-howell** [comment]
> Thanks Rich. I saw that syntax in another page, but I felt I would get to it quickly enough that it wouldn't be much of an issue. I think I'm through the 3 pages I wanted to add now as far as content goes. It's ready to be further refined/proofread now and fix any formatting to make it match the rest of the docs.

I have proof read over the document, great work, added in some bits to keep it in line with the other docs, will try and come up with some templates over the weekend on how the pages should be structured. 

I have marked the watchtower doc as unavailable for now as it seems to be incomplete, if you come back to that one later we can get it into the tree. 

Thanks for you efforts on this @shall0pass I really appreciate your help.

**Pull request merged**
